[Eth]
NetworkId = 35039980
SyncMode = "full"
DisablePeerTxBroadcast = false
NoPruning = false
NoPrefetch = false
DirectBroadcast = false
DisableSnapProtocol = false
RangeLimit = false
DatabaseCache = 512
DatabaseFreezer = ""
PruneAncientData = false
TrieCleanCache = 256
TrieDirtyCache = 256
TrieTimeout = 3600000000000
SnapshotCache = 0
TriesInMemory = 128
TriesVerifyMode = "local"
Preimages = false
FilterLogCacheSize = 0
EnablePreimageRecording = false
RPCGasCap = 50000000
RPCEVMTimeout = 5000000000
RPCTxFeeCap = 1e+00

[Eth.Miner]
GasFloor = 30000000
GasCeil = 40000000
GasPrice = 10000000000
Recommit = 10000000000
VoteEnable = false
DisableVoteAttestation = false

[Eth.TxPool]
Locals = []
NoLocals = true
Journal = "transactions.rlp"
Rejournal = 3600000000000
PriceLimit = 10000000000
PriceBump = 10
AccountSlots = 5000
GlobalSlots = 32768
AccountQueue = 512
GlobalQueue = 32768
Lifetime = 86400000000000

[Eth.GPO]
Blocks = 20
Percentile = 60
MaxHeaderHistory = 1024
MaxBlockHistory = 1024
OracleThreshold = 20

[Node]
DataDir = "/home/omdadmin/bsc-testnode/node_data"
InsecureUnlockAllowed = true
NoUSB = true
IPCPath = "geth.ipc"
HTTPHost = "0.0.0.0"
HTTPPort = 9545
HTTPVirtualHosts = ["*"]
HTTPModules = ["eth", "net", "web3", "txpool", "parlia", "debug"]
WSHost = "0.0.0.0"
WSPort = 9546
WSModules = ["net", "web3", "eth", "txpool"]
WSOrigins = ["*"]
[Node.P2P]
MaxPeers = 50
NoDiscovery = false
BootstrapNodes = []
StaticNodes = []
TrustedNodes = []
ListenAddr = ":31303"
EnableMsgEvents = false

[Node.HTTPTimeouts]
ReadTimeout = 30000000000
ReadHeaderTimeout = 0
WriteTimeout = 30000000000
IdleTimeout = 120000000000

